## spring configs
server:
  port: 5000

spring:
  datasource:
    username: admin
    url: jdbc:mysql://localhost:3306/quotesData
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    pathMatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddlAuto: update
    show-sql: true